#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 8.1' (SVN-20170428 / r11236) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2017, Gerard Beekmans

WGETLIST="http://ftp.gnu.org/gnu/dejagnu/dejagnu-1.6.tar.gz"
MD5SUMLIST="1fdc2eb0d592c4f89d82d24dfdf02f0b"

###################################################
preparation() { # CONSTRUCTING A TEMPORARY SYSTEM #
###################################################

./configure --prefix=/tools

make install

#################
} # END OF FILE #
#################

