#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 8.1' (SVN-20170428 / r11236) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2017, Gerard Beekmans

WGETLIST="http://downloads.sourceforge.net/project/e2fsprogs/e2fsprogs/v1.43.4/e2fsprogs-1.43.4.tar.gz"
MD5SUMLIST="0bd1c74f357f6e9ae2ab6fa6229b9aea"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

mkdir -v build
cd build

LIBS=-L/tools/lib                    \
CFLAGS=-I/tools/include              \
PKG_CONFIG_PATH=/tools/lib/pkgconfig \
../configure --prefix=/usr           \
             --bindir=/bin           \
             --with-root-prefix=""   \
             --enable-elf-shlibs     \
             --disable-libblkid      \
             --disable-libuuid       \
             --disable-uuidd         \
             --disable-fsck

make

make DESTDIR=${FAKEROOT} install

make DESTDIR=${FAKEROOT} install-libs

chmod -v u+w ${FAKEROOT}/usr/lib/{libcom_err,libe2p,libext2fs,libss}.a

gunzip -v ${FAKEROOT}/usr/share/info/libext2fs.info.gz
# (*) 'install-info' will automatically be done in post-installation
#install-info --dir-file=/usr/share/info/dir ${FAKEROOT}/usr/share/info/libext2fs.info

makeinfo -o      doc/com_err.info ../lib/et/com_err.texinfo
install -v -m644 doc/com_err.info ${FAKEROOT}/usr/share/info
# (*) 'install-info' will automatically be done in post-installation
#install-info --dir-file=/usr/share/info/dir ${FAKEROOT}/usr/share/info/com_err.info

#################
} # END OF FILE #
#################

