#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 8.1' (SVN-20170428 / r11236) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2017, Gerard Beekmans

WGETLIST="http://ftp.gnu.org/gnu/findutils/findutils-4.6.0.tar.gz"
MD5SUMLIST="9936aa8009438ce185bea2694a997fc1"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i 's/test-lock..EXEEXT.//' tests/Makefile.in

./configure --prefix=/usr --localstatedir=/var/lib/locate

make

make DESTDIR=${FAKEROOT} install

mv -v ${FAKEROOT}/usr/bin/find ${FAKEROOT}/bin
sed -i 's|find:=${BINDIR}|find:=/bin|' ${FAKEROOT}/usr/bin/updatedb

######################################################
}; preparation() { # CONSTRUCTING A TEMPORARY SYSTEM #
######################################################

./configure --prefix=/tools

make

make install

#################
} # END OF FILE #
#################

