#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 8.1' (SVN-20170428 / r11236) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2017, Gerard Beekmans

WGETLIST="http://ftp.gnu.org/gnu/gdbm/gdbm-1.13.tar.gz"
MD5SUMLIST="8929dcda2a8de3fd2367bdbf66769376"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr \
            --disable-static \
            --enable-libgdbm-compat

make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

