#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 8.1' (SVN-20170428 / r11236) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2017, Gerard Beekmans

WGETLIST="http://ftp.gnu.org/gnu/gperf/gperf-3.1.tar.gz"
MD5SUMLIST="9e251c0a618ad0824b51117d5d9db87e"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --docdir=/usr/share/doc/gperf-3.1

make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

