#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 8.1' (SVN-20170428 / r11236) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2017, Gerard Beekmans

WGETLIST="http://ftp.gnu.org/gnu/inetutils/inetutils-1.9.4.tar.xz"
MD5SUMLIST="87fef1fa3f603aef11c41dcc097af75e"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr        \
            --localstatedir=/var \
            --disable-logger     \
            --disable-whois      \
            --disable-rcp        \
            --disable-rexec      \
            --disable-rlogin     \
            --disable-rsh        \
            --disable-servers

make

make DESTDIR=${FAKEROOT} install

mv -v ${FAKEROOT}/usr/bin/{hostname,ping,ping6,traceroute} ${FAKEROOT}/bin
mv -v ${FAKEROOT}/usr/bin/ifconfig ${FAKEROOT}/sbin

#################
} # END OF FILE #
#################

