#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 8.1' (SVN-20170428 / r11236) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2017, Gerard Beekmans

WGETLIST="https://www.kernel.org/pub/linux/utils/kbd/kbd-2.0.4.tar.xz
          http://www.linuxfromscratch.org/patches/lfs/8.1/kbd-2.0.4-backspace-1.patch"
MD5SUMLIST="c1635a5a83b63aca7f97a3eab39ebaa6
            f75cca16a38da6caa7d52151f7136895"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

patch -Np1 -i ../kbd-2.0.4-backspace-1.patch

sed -i 's/\(RESIZECONS_PROGS=\)yes/\1no/g' configure
sed -i 's/resizecons.8 //' docs/man/man8/Makefile.in

PKG_CONFIG_PATH=/tools/lib/pkgconfig ./configure --prefix=/usr --disable-vlock

make

make DESTDIR=${FAKEROOT} install

mkdir -v       ${FAKEROOT}/usr/share/doc/kbd-2.0.4
cp -R -v docs/doc/* ${FAKEROOT}/usr/share/doc/kbd-2.0.4

#################
} # END OF FILE #
#################

