#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 8.1' (SVN-20170428 / r11236) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2017, Gerard Beekmans

WGETLIST="http://ftp.gnu.org/gnu//ncurses/ncurses-6.0.tar.gz"
MD5SUMLIST="ee13d052e1ead260d7c28071f46eefb1"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i '/LIBTOOL_INSTALL/d' c++/Makefile.in

./configure --prefix=/usr           \
            --mandir=/usr/share/man \
            --with-shared           \
            --without-debug         \
            --without-normal        \
            --enable-pc-files       \
            --enable-widec

make

make DESTDIR=${FAKEROOT} install

mv -v ${FAKEROOT}/usr/lib/libncursesw.so.6* ${FAKEROOT}/lib

ln -sfv ../../lib/$(readlink ${FAKEROOT}/usr/lib/libncursesw.so) ${FAKEROOT}/usr/lib/libncursesw.so

for lib in ncurses form panel menu ; do
    rm -vf                    ${FAKEROOT}/usr/lib/lib${lib}.so
    echo "INPUT(-l${lib}w)" > ${FAKEROOT}/usr/lib/lib${lib}.so
    ln -sfv ${lib}w.pc        ${FAKEROOT}/usr/lib/pkgconfig/${lib}.pc
done

rm -vf                     ${FAKEROOT}/usr/lib/libcursesw.so
echo "INPUT(-lncursesw)" > ${FAKEROOT}/usr/lib/libcursesw.so
ln -sfv libncurses.so      ${FAKEROOT}/usr/lib/libcurses.so

mkdir -v       ${FAKEROOT}/usr/share/doc/ncurses-6.0
cp -v -R doc/* ${FAKEROOT}/usr/share/doc/ncurses-6.0

######################################################
}; preparation() { # CONSTRUCTING A TEMPORARY SYSTEM #
######################################################

sed -i s/mawk// configure

./configure --prefix=/tools \
            --with-shared   \
            --without-debug \
            --without-ada   \
            --enable-widec  \
            --enable-overwrite

make

make install

#################
} # END OF FILE #
#################

