#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 8.1' (SVN-20170428 / r11236) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2017, Gerard Beekmans

WGETLIST="http://sourceforge.net/projects/procps-ng/files/Production/procps-ng-3.3.12.tar.xz"
MD5SUMLIST="957e42e8b193490b2111252e4a2b443c"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr                            \
            --exec-prefix=                           \
            --libdir=/usr/lib                        \
            --docdir=/usr/share/doc/procps-ng-3.3.12 \
            --disable-static                         \
            --disable-kill

make

make DESTDIR=${FAKEROOT} install

mv -v ${FAKEROOT}/usr/lib/libprocps.so.* ${FAKEROOT}/lib
ln -sfv ../../lib/$(readlink ${FAKEROOT}/usr/lib/libprocps.so) ${FAKEROOT}/usr/lib/libprocps.so

#################
} # END OF FILE #
#################

