#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 8.1' (SVN-20170428 / r11236) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2017, Gerard Beekmans

WGETLIST="https://github.com/shadow-maint/shadow/releases/download/4.4/shadow-4.4.tar.xz"
MD5SUMLIST="c06f8c2571b44899e60662f9ad259dd6"
POSTINST="now"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i 's/groups$(EXEEXT) //' src/Makefile.in
find man -name Makefile.in -exec sed -i 's/groups\.1 / /'   {} \;
find man -name Makefile.in -exec sed -i 's/getspnam\.3 / /' {} \;
find man -name Makefile.in -exec sed -i 's/passwd\.5 / /'   {} \;

sed -i -e 's@#ENCRYPT_METHOD DES@ENCRYPT_METHOD SHA512@' \
       -e 's@/var/spool/mail@/var/mail@' etc/login.defs

echo '--- src/useradd.c   (old)
+++ src/useradd.c   (new)
@@ -2027,6 +2027,8 @@
        is_shadow_grp = sgr_file_present ();
 #endif
 
+       get_defaults ();
+
        process_flags (argc, argv);
 
 #ifdef ENABLE_SUBIDS
@@ -2036,8 +2038,6 @@
            (!user_id || (user_id <= uid_max && user_id >= uid_min));
 #endif                         /* ENABLE_SUBIDS */
 
-       get_defaults ();
-
 #ifdef ACCT_TOOLS_SETUID
 #ifdef USE_PAM
        {' | patch -p0 -l

sed -i 's/1000/999/' etc/useradd

sed -i -e '47 d' -e '60,65 d' libmisc/myname.c

./configure --sysconfdir=/etc --with-group-name-max-length=32

make

make DESTDIR=${FAKEROOT} install

mv -v ${FAKEROOT}/usr/bin/passwd ${FAKEROOT}/bin

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

pwconv

grpconv

sed -i 's/yes/no/' /etc/default/useradd

# (*) The password for root will be set during interactive configuration.
#passwd root

#################
} # END OF FILE #
#################

