#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 8.1' (SVN-20170428 / r11236) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2017, Gerard Beekmans

WGETLIST="http://www.infodrom.org/projects/sysklogd/download/sysklogd-1.5.1.tar.gz"
MD5SUMLIST="c70599ab0d037fde724f7210c2c8d7f8"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

sed -i '/Error loading kernel symbols/{n;n;d}' ksym_mod.c
sed -i 's/union wait/int/' syslogd.c

make

make prefix=${FAKEROOT} BINDIR=${FAKEROOT}/sbin install

cat > ${FAKEROOT}/etc/syslog.conf << "EOF"
# Begin /etc/syslog.conf

auth,authpriv.* -/var/log/auth.log
*.*;auth,authpriv.none -/var/log/sys.log
daemon.* -/var/log/daemon.log
kern.* -/var/log/kern.log
mail.* -/var/log/mail.log
user.* -/var/log/user.log
*.emerg *

# End /etc/syslog.conf
EOF

#################
} # END OF FILE #
#################

