#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 8.1' (SVN-20170428 / r11236) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2017, Gerard Beekmans

WGETLIST="http://ftp.gnu.org/gnu/tar/tar-1.29.tar.xz"
MD5SUMLIST="a1802fec550baaeecff6c381629653ef"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

FORCE_UNSAFE_CONFIGURE=1  \
./configure --prefix=/usr \
            --bindir=/bin

make

make DESTDIR=${FAKEROOT} install
make DESTDIR=${FAKEROOT} -C doc install-html docdir=/usr/share/doc/tar-1.29

######################################################
}; preparation() { # CONSTRUCTING A TEMPORARY SYSTEM #
######################################################

./configure --prefix=/tools

make

make install

#################
} # END OF FILE #
#################

