#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 8.1' (SVN-20170428 / r11236) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2017, Gerard Beekmans

WGETLIST="http://ftp.gnu.org/gnu/texinfo/texinfo-6.3.tar.xz"
MD5SUMLIST="32baefe5c7080dfb512a4eac5ce67b2a"
POSTINST="true"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr --disable-static

make

make DESTDIR=${FAKEROOT} install

make DESTDIR=${FAKEROOT} TEXMF=/usr/share/texmf install-tex

###################################################
}; postinst() { # POST-INSTALLATION CONFIGURATION #
###################################################

pushd /usr/share/info
# (*) Without '-f', 'rm' would fail if 'dir' does not exist
#rm -v dir
rm -vf dir
for f in *
  do install-info $f dir 2>/dev/null
done
popd

######################################################
}; preparation() { # CONSTRUCTING A TEMPORARY SYSTEM #
######################################################

./configure --prefix=/tools

make

make install

#################
} # END OF FILE #
#################

