#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 8.1' (SVN-20170428 / r11236) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2017, Gerard Beekmans

WGETLIST="ftp://ftp.vim.org/pub/vim/unix/vim-8.0.586.tar.bz2"
MD5SUMLIST="b35e794140c196ff59b492b56c1e73db"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

echo '#define SYS_VIMRC_FILE "/etc/vimrc"' >> src/feature.h

./configure --prefix=/usr

make

make DESTDIR=${FAKEROOT} install

ln -sv vim ${FAKEROOT}/usr/bin/vi
for L in  ${FAKEROOT}/usr/share/man/{,*/}man1/vim.1; do
    ln -sv vim.1 $(dirname $L)/vi.1
done

ln -sv ../vim/vim80/doc ${FAKEROOT}/usr/share/doc/vim-8.0.586

cat > ${FAKEROOT}/etc/vimrc << "EOF"
" Begin /etc/vimrc

set nocompatible
set backspace=2
set mouse=r
syntax on
if (&term == "xterm") || (&term == "putty")
  set background=dark
endif


" End /etc/vimrc
EOF

#################
} # END OF FILE #
#################

