#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 8.1' (SVN-20170428 / r11236) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2017, Gerard Beekmans

WGETLIST="http://cpan.metacpan.org/authors/id/T/TO/TODDR/XML-Parser-2.44.tar.gz"
MD5SUMLIST="af4813fe3952362451201ced6fbce379"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

perl Makefile.PL

make

make DESTDIR=${FAKEROOT} install

#################
} # END OF FILE #
#################

