#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 8.1' (SVN-20170428 / r11236) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2017, Gerard Beekmans

WGETLIST="http://tukaani.org/xz/xz-5.2.4.tar.xz"
MD5SUMLIST="003e4d0b1b1899fc6e3000b24feddf7c"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/xz-5.2.4

make

make DESTDIR=${FAKEROOT} install
mv -v   ${FAKEROOT}/usr/bin/{lzma,unlzma,lzcat,xz,unxz,xzcat} ${FAKEROOT}/bin
mv -v ${FAKEROOT}/usr/lib/liblzma.so.* ${FAKEROOT}/lib
ln -svf ../../lib/$(readlink ${FAKEROOT}/usr/lib/liblzma.so) ${FAKEROOT}/usr/lib/liblzma.so

######################################################
}; preparation() { # CONSTRUCTING A TEMPORARY SYSTEM #
######################################################

./configure --prefix=/tools

make

make install

#################
} # END OF FILE #
#################

