#!/bin/bash

# The instructions in this file are extracted from
# 'Linux From Scratch 8.1' (SVN-20170428 / r11236) but are modified for use
# with LFScript 4 which installs the software to a fake root directory.
#
# Linux From Scratch is released under the MIT license.
# Copyright (C) 1999-2017, Gerard Beekmans

WGETLIST="http://zlib.net/zlib-1.2.11.tar.xz"
MD5SUMLIST="85adef240c5f370b308da8c938951a68"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

./configure --prefix=/usr

make

make DESTDIR=${FAKEROOT} install

mv -v ${FAKEROOT}/usr/lib/libz.so.* ${FAKEROOT}/lib
ln -sfv ../../lib/$(readlink ${FAKEROOT}/usr/lib/libz.so) ${FAKEROOT}/usr/lib/libz.so

#################
} # END OF FILE #
#################

